use std::{fmt::Debug, sync::Arc};

use next_web_core::{
    async_trait,
    traits::http::{http_request::HttpRequest, http_response::HttpResponse},
};

use crate::{
    core::{Authentication, AuthenticationError},
    web::{
        authentication::session::SessionAuthenticationStrategy,
        csrf::{
            csrf_token_repository::load_deferred_token, CsrfTokenRepository,
            CsrfTokenRequestHandler, XorCsrfTokenRequestAttributeHandler,
        },
    },
};

/// CsrfAuthenticationStrategy is in charge of removing the
/// CsrfToken upon authenticating. A new CsrfToken will then be generated by the framework upon the next request.
pub struct CsrfAuthenticationStrategy {
    token_repository: Arc<dyn CsrfTokenRepository>,
    request_handler: Arc<dyn CsrfTokenRequestHandler>,
}

impl CsrfAuthenticationStrategy {
    /// Creates a new instance
    pub fn new(token_repository: Arc<dyn CsrfTokenRepository>) -> Self {
        Self {
            token_repository,
            request_handler: Arc::new(XorCsrfTokenRequestAttributeHandler::default()),
        }
    }

    /// Specify a CsrfTokenRequestHandler to use for making the CsrfToken available as a request attribute.
    pub fn set_request_handler(&mut self, request_handler: Arc<dyn CsrfTokenRequestHandler>) {
        self.request_handler = request_handler;
    }
}

#[async_trait]
impl SessionAuthenticationStrategy for CsrfAuthenticationStrategy {
    async fn on_authentication(
        &self,
        _authentication: &Arc<dyn Authentication>,
        req: &mut dyn HttpRequest,
        resp: &mut dyn HttpResponse,
    ) -> Result<(), AuthenticationError> {
        let contains_token = self.token_repository.load_token(req).await.is_some();
        if contains_token {
            self.token_repository.save_token(None, req, resp).await;

            let mut deferred_csrf_token =
                load_deferred_token(self.token_repository.clone(), req, resp);
            self.request_handler
                .handle(req, resp, &mut deferred_csrf_token);
            tracing::debug!("Replaced CSRF Token");
        }

        Ok(())
    }
}

impl Debug for CsrfAuthenticationStrategy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CsrfAuthenticationStrategy")
            .field("token_repository", &"none")
            .field("request_handler", &"none")
            .finish()
    }
}
