use std::sync::Arc;

use next_web_core::{
    async_trait,
    traits::http::{http_request::HttpRequest, http_response::HttpResponse},
};

use crate::{
    core::Authentication,
    web::{authentication::logout::LogoutHandler, csrf::CsrfTokenRepository},
};

/// CsrfLogoutHandler is in charge of removing the CsrfToken upon logout.
/// A new CsrfToken will then be generated by the framework upon the next request.
#[derive(Clone)]
pub struct CsrfLogoutHandler {
    csrf_token_repository: Arc<dyn CsrfTokenRepository>,
}

impl CsrfLogoutHandler {
    /// Creates a new instance
    pub fn new(csrf_token_repository: Arc<dyn CsrfTokenRepository>) -> Self {
        Self {
            csrf_token_repository,
        }
    }
}

#[async_trait]
impl LogoutHandler for CsrfLogoutHandler {
    /// Clears the CsrfToken
    async fn logout(
        &self,
        request: &mut dyn HttpRequest,
        response: &mut dyn HttpResponse,
        _authentication: Option<&Arc<dyn Authentication>>,
    ) {
        self.csrf_token_repository
            .save_token(None, request, response)
            .await
            .inspect_err(|err| {
                tracing::error!("Failed to save CSRF token: {}", err);
            })
            .ok();
    }
}
