routes:
  - id: Test
    uri: lb://UserService
    predicates: 
      - Path=/test/**
      - Header=X-Request-Id
    metadata:
      connect_timeout: 100
  - id: Test1
    uri: lb://UserService
    predicates: 
      - Path=/test/**
      - Header=X-Request-Id
    metadata:
      connect_timeout: 100
