[package]
name = "next-web-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true}
serde_yaml = { workspace = true }
hashbrown = { workspace = true }
rust-embed-for-web = { workspace = true }
dyn-clone = { workspace = true }

inventory = {workspace = true}

async-trait ={ workspace = true }