[package]
name = "next-web-shiro"
version = "0.1.0"
edition = "2024"

[dependencies]
next-web-core.workspace = true

tokio.workspace     = true
dashmap.workspace   = true
tracing.workspace   = true
serde.workspace     = true
axum.workspace      = true