[package]
name = "fast-excel"
version = "0.1.0"
edition = "2024"

[dependencies]
next-web-core = { workspace = true }

tokio       = { workspace = true }
tracing     = { workspace = true }
chrono      = { workspace = true }
once_cell   = { workspace = true }
regex       = { workspace = true }
bigdecimal  = { workspace = true }
rust_decimal = { version = "1.39.0" }

# rust_xlsxwriter = { workspace = true }
# umya-spreadsheet = { workspace = true }
# calamine = { workspace = true }


[features]
default = ["async"]
async   = []
