[package]
name = "next-web-pay-alipay"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono          = { workspace = true }
form_urlencoded = { workspace = true }
urlencoding     = { workspace = true }
reqwest         = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
thiserror       = { workspace = true }
rand            = { workspace = true }

base64          = { workspace = true }
sha2            = { workspace = true, features = ["oid"] }

aes             = { workspace = true }
aes-gcm         = { workspace = true }
rsa             = { workspace = true, features = ["pem"] }

[dev-dependencies]
tokio           = { workspace = true }