[workspace]
members = [
    "next-web",
    "next-web-core",
    "next-web-ai",
    "next-web-document",
    "next-web-gateway",
    "next-web-mail",
    "next-web-macros",
    "next-web-open-api",
    "next-web-retry",
    "next-web-security",
    "next-web-sms",
    "next-web-tests",
    "next-web-utils",
    "next-web-websocket",
    "next-web-mq/next-web-mq-kafka",
    "next-web-mq/next-web-mq-rabbitmq",
    "next-web-mq/next-web-mq-rocketmq",
    "next-web-data/next-web-data-redis",
    "next-web-wechat",
    "next-web-api-doc",
    "next-web-actuator",
    "next-web-pay/next-web-pay-alipay",
    "next-web-pay/next-web-pay-wechatpay",
    "next-web-xxl-job",
    "next-web-state-machine",
    "next-web-id-generator"
]
exclude = ["next-web-code-generator"]
resolver = "2"

[workspace.package]
rust-version = "1.92.0"
edition = "2024"
version = "0.1.0"
authors = ["Listening <yuenxillar@163.com>"]
keywords = ["http", "web", "framework"]
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://crates.io/crates/next-web"
repository = "https://github.com/yuenxillar/next-web"
include = ["**/*.rs", "Cargo.toml"]

[workspace.lints.rust]
unsafe_code = "forbid"

rust_2018_idioms = { level = "warn", priority = -1 }
missing_docs = "warn"
unreachable_pub = "warn"


[workspace.lints.clippy]
await_holding_lock = "warn"
if_let_mutex = "warn"
mem_forget = "warn"
enum_glob_use = "warn"
macro_use_imports = "warn"
match_same_arms = "warn"
single_match_else = "warn"
implicit_clone = "warn"
redundant_clone = "warn"
inefficient_to_string = "warn"
str_to_string = "warn"
uninlined_format_args = "warn"
option_option = "warn"

todo = "warn"

[workspace.dependencies]
# next dependencies
next-web-ai = { version = "0.1.0", path = "./next-web-ai" }
next-web-core = { version = "0.1.5", path = "./next-web-core" }
next-web = { version = "0.1.7", path = "./next-web" }
next-web-api-doc = { version = "0.1.0", path = "./next-web-api-doc" }
next-web-document = { version = "0.1.0", path = "./next-web-document" }
next-web-mail = { version = "0.1.0", path = "./next-web-mail" }
next-web-ip = { version = "0.1.0", path = "./next-web-ip" }
next-web-macros = { version = "0.2.0", path = "./next-web-macros" }
next-web-mqtt = { version = "0.1.4", path = "./next-web-mqtt" }
next-web-open-api = { version = "0.1.0", path = "./next-web-open-api" }
next-web-retry = { version = "0.1.0", path = "./next-web-retry" }
next-web-security = { version = "0.1.0", path = "./next-web-security" }
next-web-sms = { version = "0.1.0", path = "./next-web-sms" }
next-web-tests = { version = "0.1.0", path = "./next-web-tests" }
next-web-utils = { version = "0.1.0", path = "./next-web-utils" }
next-web-websocket = { version = "0.1.2", path = "./next-web-websocket" }
next-web-mq-kafka = { version = "0.1.0", path = "./next-web-mq/next-web-mq-kafka" }
next-web-mq-rabbitmq = { version = "0.1.0", path = "./next-web-mq/next-web-mq-rabbitmq" }
next-web-mq-rocketmq = { version = "0.1.0", path = "./next-web-mq/next-web-mq-rocketmq" }
next-web-wechat = { version = "0.1.0", path = "./next-web-wechat" }
next-web-xxl-job = { version = "0.1.0", path = "./next-web-xxl-job" }
next-web-state-machine = { version = "0.1.0", path = "./next-web-state-machine" }

# next-web-common = { version = "0.1.0" }
# next-web-mq = {  version = "0.1.0", path = "./next-web-mq"}

rudi-dev = { version = "0.8.7", path = "./rudi-main/rudi-dev" }

# main dependencies
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
tokio-util = { version = "0.7.15" }
async-stream = { version = "0.3.6" }
axum = { version = "0.8.4" }
tower-http = { version = "0.6.8" }
axum-prometheus = { version = "0.7.0" }
axum-core = { version = "0.5.2" }
oauth2 = { version = "5.0.0" }

mimalloc = { version = "0.1.47" }
jemallocator = { version = "0.5.4" }

# serialization and deserialization
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = { version = "0.9.34" }
serde_json = { version = "1.0.133" }
serde_repr = { version = "0.1.20" }
serde_with = { version = "3.17.0" }
serde_path_to_error = { version = "0.1.17" }
quick-xml = { version = "0.37.4", features = ["serialize"] }
strum = { version = "0.27", features = ["derive"] }

utoipa = { version = "5.4.0" }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "reqwest"] }

# document
calamine = { version = "0.26.1" }
rust_xlsxwriter = { version = "0.87.0", features = ["serde", "ryu"] }
umya-spreadsheet = { version = "2.3.0" }
csv = { version = "1.3.1" }
printpdf = { version = "0.8.2" }

# proxy
pingora         = { version = "0.8.0", features = ["lb", "proxy"] }
pingora-limits  = "0.8.0"

# pay
wechat-pay-rust-sdk = { version = "0.2.18" }


arc-swap = { version = "1.8.2" }
byteorder = { version = "1.5.0" }
encoding = { version = "0.2.33" }
mime = { version = "0.3.17" }
bigdecimal = { version = "0.4.9" }
headers = { version = "0.4.1" }
form_urlencoded = { version = "1.2.2" }
validator = { version = "0.20.0", features = ["derive"] }
reqwest = { version = "0.13.3", features = ["json", "query", "form"] }
reqwest-websocket   = { version = "0.6.0"}
once_cell = { version = "1.20.2" }
async-trait = { version = "0.1.88" }
chrono = { version = "0.4.40" }
chrono-tz = { version = "0.10.4" }
hashbrown = { version = "0.15.2", features = ["serde"] }
regex = { version = "1.11.1" }
jsonwebtoken = { version = "9.3.0" }
rust-embed = { version = "8.11.0", features = ["include-exclude"] }
clap = { version = "4.5.37", features = ["derive"] }
matchit = { version = "0.8.4" }
bcrypt = { version = "0.16.0" }
rand = { version = "0.8.5" }
uuid = { version = "1.16.0", features = ["v4"] }
tokio-cron-scheduler = { version = "0.13.0" }
http-body-util = { version = "0.1.2" }
parking_lot = { version = "0.12.3" }
flume = { version = "0.11.1" }
dyn-clone = { version = "1.0.19" }
lettre = { version = "0.11.15", features = [
    "smtp-transport",
    "builder",
    "tokio1-native-tls",
] }
indexmap = { version = "2.9.0" }
hmac = { version = "0.12.1" }
urlencoding = { version = "2.1.3" }
dashmap = { version = "6.1.0", features = ["serde"] }
bytes = { version = "1.10.1" }
sys-locale = { version = "0.3.2" }
ipnetwork = { version = "0.21.1" }
sysinfo = { version = "0.38.4" }

thiserror = { version = "2.0.8" }
anyhow = { version = "1.0.94" }

futures = { version = "0.3.31" }
futures-util = { version = "0.3.31" }
futures-core = { version = "0.3.31" }

sha1 = { version = "0.10.6" }
sha2 = { version = "0.10.8" }
md5 = { version = "0.7.0" }
md2 = { version = "0.10.2" }
hex = { version = "0.4.3" }
base64 = { version = "0.22.1" }
aes-gcm = { version = "0.10.3" }
aes = { version = "0.8.4" }
scrypt  = { version = "0.11.0" }
rsa     = { version = "0.9.10" }

# data
rbs = { version = "4.6.2" }
rbatis = { version = "4.8.1" }
rbdc = { version = "4.6.1", default-features = false }
rbdc-pg = { version = "4.6.2" }
rbdc-mysql = { version = "4.6.1" }
rbdc-pool-fast = { version = "4.6.1" }

mongodb = { version = "3.2.0", features = ["zstd-compression"] }
redis = { version = "1.2.0", features = ["tokio-comp", "json"] }
rslock = { version = "0.7.1", default-features = false, features = [
    "tokio-comp",
] }
deadpool-redis = { version = "0.20.0" }
minio-rsc = { version = "0.2.3" }
rumqttc = { version = "0.24.0" }
elasticsearch = { version = "9.0.0-alpha.1", features = [] }

# mq
rocketmq = { version = "5.0.0" }
amqprs = { version = "2.1.1", features = ["traces"] }

# macro dependencies
proc-macro2 = { version = "1" }
quote = { version = "1" }
syn = { version = "2" }
from-attr = { version = "0.1.3" }

# optional dependencies
inventory = { version = "0.3.21" }
tracing = { version = "0.1" }
tracing-appender = { version = "0.2" }
tracing-subscriber = { version = "0.3.0", features = [
    "fmt",
    "env-filter",
    "json",
    "chrono",
] }


[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 'z'    # Optimize for size
