[workspace]
resolver = "2"

members = [ 
    "next-code-builder", 
    "next-web-framework/Cargo.toml",
    "next-test-server"
]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 'z' # Optimize for size


 [profile.release.package.next-test-server]
 opt-level = 3
