[workspace]
resolver = "2"

members = [
    "next-code-builder",
    "next-web-framework/Cargo.toml",
    "railway-12306",
]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 'z'    # Optimize for size


[profile.release.package.railway-12306]
opt-level = 3
