[package]
name = "next-web-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
next-web-core = { workspace = true }
bytes = { workspace = true }
futures-core = { workspace = true}


[dev-dependencies]
tokio.workspace = true
reqwest.workspace = true


[features]
default = ["deep-seek"]

deep-seek = []
