[package]
name = "next-web-tests"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
include.workspace = true
readme.workspace = true

[dependencies]
next-web        = { path = "../next-web", version = "*", features = ["full"]}
next-web-core   = { path = "../next-web-core", version = "*" }

tokio           = { workspace = true, features = ["sync"]}
serde           = { workspace = true }
serde_json      = { workspace = true }

rust_xlsxwriter = { workspace = true }
axum            = { version = "0.8.4", features = ["default", "multipart", "query"] }
tokio-util      = { workspace = true }
futures         = { workspace = true }
utoipa          = { workspace = true }

tracing         ={ workspace = true}


# next-web-data-database = { path = "../next-web-data-database", version = "0.1.0" }
# next-web-data-mongodb = { path = "../next-web-data-mongodb", version = "0.1.0" }

[dev-dependencies]
next-web-ai             = { path = "../next-web-ai", version = "*", features = ["deep-seek"]}
next-web-mqtt           = { path = "../next-web-mqtt", version = "*" }
next-web-websocket      = { path = "../next-web-websocket", version = "*" }
next-web-security       = { path = "../next-web-security", version = "*" }
next-web-data-redis     = { path = "../next-web-data/next-web-data-redis", version = "*", features = []}
next-web-data-database  = { path = "../next-web-data/next-web-data-database", version = "*" }
next-web-state-machine  = { path = "../next-web-state-machine", version = "*" }
next-web-xxl-job        = { path = "../next-web-xxl-job", version = "*" }
next-web-mail           = { path = "../next-web-mail", version = "*" }
next-web-ip             = { path = "../next-web-ip", version = "0.1.0" }
next-web-document       = { path = "../next-web-document", version = "0.1.0", features = [] }
next-web-retry          = { path = "../next-web-retry", version = "*"}
next-web-pay-alipay     = { path = "../next-web-pay/next-web-pay-alipay", version = "*" }
next-web-context        = { path = "../next-web-context", version = "*" }

[features]
enable-api-doc = ["next-web/enable-api-doc"]
