[package]
name = "next-web-data-mongodb"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
next-web-core = { workspace = true }
rudi-dev = { workspace = true }
tracing = { workspace = true}

mongodb = { workspace = true }