use std::{
    ops::{Deref, DerefMut},
    sync::Arc,
};

use next_web_core::util::http_method::HttpMethod;

use crate::{
    config::{
        security_configurer::SecurityConfigurer,
        web::{
            configurers::{
                BaseAuthenticationFilterConfigurer, BaseAuthenticationFilterConfigurerExt,
                ErrorHandlingConfigurer,
            },
            http_security_builder::HttpSecurityBuilder,
        },
    },
    core::authority::FactorGrantedAuthority,
    web::{
        authentication::{
            forward_authentication_failure_handler::ForwardAuthenticationFailureHandler,
            forward_authentication_success_handler::ForwardAuthenticationSuccessHandler,
            ui::DefaultLoginPageGeneratingFilter, UsernamePasswordAuthenticationFilter,
        },
        default_security_filter_chain::DefaultSecurityFilterChain,
        util::matcher::{RequestMatcher, DEFAULT_BUILDER},
    },
};

/// Adds form based authentication. All attributes have reasonable defaults making all parameters are optional.
/// If no loginPage(String) is specified, a default login page will be generated by the framework.
#[derive(Clone)]
pub struct FormLoginConfigurer<H>
where
    H: HttpSecurityBuilder<H>,
{
    inner: BaseAuthenticationFilterConfigurer<H, Self, UsernamePasswordAuthenticationFilter>,
}

impl<H> FormLoginConfigurer<H>
where
    H: HttpSecurityBuilder<H>,
{
    /// The HTTP parameter to look for the username when performing authentication. Default
    /// is `"username"`.
    ///
    /// # Arguments
    ///
    /// * `username_parameter` - the HTTP parameter to look for the username when
    ///   performing authentication
    ///
    /// # Returns
    ///
    /// The `FormLoginConfigurer` for additional customization
    pub fn username_parameter(&mut self, username_parameter: &str) -> &mut Self {
        self.get_authentication_filter_mut()
            .map(|filter| filter.set_username_parameter(username_parameter));

        self
    }

    /// The HTTP parameter to look for the password when performing authentication. Default
    /// is `"password"`.
    ///
    /// # Arguments
    ///
    /// * `password_parameter` - the HTTP parameter to look for the password when
    ///   performing authentication
    ///
    /// # Returns
    ///
    /// The `FormLoginConfigurer` for additional customization
    pub fn password_parameter(&mut self, password_parameter: &str) -> &mut Self {
        self.get_authentication_filter_mut()
            .map(|filter| filter.set_password_parameter(password_parameter));

        self
    }

    /// Forward Authentication Failure Handler
    ///
    /// # Arguments
    ///
    /// * `forward_url` - the target URL in case of failure
    ///
    /// # Returns
    ///
    /// The `FormLoginConfigurer` for additional customization
    pub fn failure_forward_url(&mut self, forward_url: &str) -> &mut Self {
        self.failure_handler(Arc::new(ForwardAuthenticationFailureHandler::new(
            forward_url,
        )));

        self
    }

    /// Forward Authentication Success Handler
    ///
    /// # Arguments
    ///
    /// * `forward_url` - the target URL in case of success
    ///
    /// # Returns
    ///
    /// The `FormLoginConfigurer` for additional customization
    pub fn success_forward_url(&mut self, forward_url: &str) -> &mut Self {
        self.success_handler(Arc::new(ForwardAuthenticationSuccessHandler::new(
            forward_url,
        )));

        self
    }

    /// Gets the HTTP parameter that is used to submit the username.
    ///
    /// # Returns
    ///
    /// The HTTP parameter that is used to submit the username
    fn get_username_parameter(&self) -> &str {
        self.get_authentication_filter()
            .map(|filter| filter.get_username_parameter())
            .unwrap_or_default()
    }

    /// Gets the HTTP parameter that is used to submit the password.
    ///
    /// # Returns
    ///
    /// The HTTP parameter that is used to submit the password
    fn get_password_parameter(&self) -> &str {
        self.get_authentication_filter()
            .map(|filter| filter.get_password_parameter())
            .unwrap_or_default()
    }

    /// If available, initializes the `DefaultLoginPageGeneratingFilter` shared
    /// object.
    ///
    /// # Arguments
    ///
    /// * `http` - the `HttpSecurityBuilder` to use
    pub(crate) fn init_default_login_filter(&mut self, http: &mut H) {
        if let Some(login_page_generating_filter) =
            http.shared_object_mut::<DefaultLoginPageGeneratingFilter>()
        {
            if !self.is_custom_login_page() {
                login_page_generating_filter.set_form_login_enabled(true);
                login_page_generating_filter.set_username_parameter(self.get_username_parameter());
                login_page_generating_filter.set_password_parameter(self.get_password_parameter());
                login_page_generating_filter.set_login_page_url(self.get_login_page());

                self.get_failure_url()
                    .map(|s| login_page_generating_filter.set_failure_url(s));

                self.get_login_processing_url()
                    .map(|s| login_page_generating_filter.set_authentication_url(s));
            }
        }
    }
}

impl<H> SecurityConfigurer<DefaultSecurityFilterChain, H> for FormLoginConfigurer<H>
where
    H: HttpSecurityBuilder<H>,
    H: 'static,
{
    fn init(&mut self, http: &mut H) {
        self.inner.init(http);
        self.init_default_login_filter(http);

        // Configure exception handling
        let request_matcher = self.get_authentication_entry_point_matcher(http);
        if let Some(error_handling_configurer) = http.configurer_mut::<ErrorHandlingConfigurer<H>>()
        {
            let entry_point = self.get_authentication_entry_point();
            error_handling_configurer.default_denied_handler_for_missing_authority(
                |builer| {
                    entry_point
                        .map(|ep| builer.add_entry_point_for(ep.to_owned(), request_matcher));
                },
                FactorGrantedAuthority::PASSWORD_AUTHORITY,
            );
        }
    }

    fn configure(&mut self, http: &mut H) {
        self.inner.configure(http);
    }
}

impl<H> BaseAuthenticationFilterConfigurerExt for FormLoginConfigurer<H>
where
    H: HttpSecurityBuilder<H>,
    H: 'static,
{
    /// Specifies the URL to send users to if login is required. If used with
    /// `EnableWebSecurity` a default login page will be generated when this
    /// attribute is not specified.
    ///
    /// If a URL is specified or this is not being used in conjunction with
    /// `EnableWebSecurity`, users are required to process the specified URL to
    /// generate a login page. In general, the login page should create a form that submits
    /// a request with the following requirements to work with
    /// `UsernamePasswordAuthenticationFilter`:
    ///
    /// * It must be an HTTP POST
    /// * It must be submitted to `login_processing_url`
    /// * It should include the username as an HTTP parameter by the name of
    ///   `username_parameter`
    /// * It should include the password as an HTTP parameter by the name of
    ///   `password_parameter`
    ///
    /// # Impact on other defaults
    ///
    /// Updating this value, also impacts a number of other default values. For example,
    /// the following are the default values when only `form_login()` was specified.
    ///
    /// * `/login` GET - the login form
    /// * `/login` POST - process the credentials and if valid authenticate the user
    /// * `/login?error` GET - redirect here for failed authentication attempts
    /// * `/login?logout` GET - redirect here after successfully logging out
    ///
    /// If `"/authenticate"` was passed to this method it updates the defaults as shown below:
    ///
    /// * `/authenticate` GET - the login form
    /// * `/authenticate` POST - process the credentials and if valid authenticate the user
    /// * `/authenticate?error` GET - redirect here for failed authentication attempts
    /// * `/authenticate?logout` GET - redirect here after successfully logging out
    ///
    /// # Arguments
    ///
    /// * `login_page` - the login page to redirect to if authentication is required (i.e.
    ///   `"/login"`)
    ///
    /// # Returns
    ///
    /// The `FormLoginConfigurer` for additional customization
    fn login_page(&mut self, login_page: &str) {
        self.inner.login_page(login_page);
    }

    fn login_processing_url(&mut self, login_processing_url: &str) {
        self.inner.login_processing_url = Some(login_processing_url.into());

        let requires_authentication_request_matcher =
            self.create_login_processing_url_matcher(login_processing_url);
        self.inner.auth_filter.as_mut().map(|filter| {
            filter.set_requires_authentication_request_matcher(
                requires_authentication_request_matcher,
            )
        });
    }

    fn create_login_processing_url_matcher(
        &self,
        login_processing_url: &str,
    ) -> Arc<dyn RequestMatcher> {
        Arc::new(
            DEFAULT_BUILDER
                .get_or_init(|| Default::default())
                .matcher(Some(HttpMethod::Post), login_processing_url),
        )
    }
}

impl<H> Default for FormLoginConfigurer<H>
where
    H: HttpSecurityBuilder<H>,
{
    fn default() -> Self {
        let mut configurer = Self {
            inner: BaseAuthenticationFilterConfigurer::new(
                UsernamePasswordAuthenticationFilter::default(),
                None,
            ),
        };
        configurer
            .username_parameter("username")
            .password_parameter("password");

        configurer
    }
}

impl<H> Deref for FormLoginConfigurer<H>
where
    H: HttpSecurityBuilder<H>,
{
    type Target = BaseAuthenticationFilterConfigurer<H, Self, UsernamePasswordAuthenticationFilter>;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

impl<H> DerefMut for FormLoginConfigurer<H>
where
    H: HttpSecurityBuilder<H>,
{
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.inner
    }
}
