[package]
name = "next-web-retry"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
dyn-clone = { workspace = true }
tokio = { workspace = true, features = ["sync"]}