[package]
name = "next-web-data-minio"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
next-web-core = { workspace = true }
rudi-dev = { workspace = true }
tracing = { workspace = true}


minio-rsc = { workspace = true }