[package]
name = "next-web-dev"
version = "0.1.0"
edition = "2021"
keywords = ["http", "web", "framework"]

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
axum = { version = "0.8.1", default-features = false, features = [
    "http2",
    "json",
    "tokio",
] }
axum-server = { version = "0.7.1", features = ["tls-rustls"], optional = true }
axum-prometheus = { version = "0.7.0", optional = true }
tower-http = { version = "0.6.2", features = [
    "trace",
    "timeout",
    "limit",
    "cors",
    "catch-panic",
] }
http-body-util = "0.1.2"
tokio-cron-scheduler = { version = "0.13.0", optional = true }

serde = { version = "1.0.216", features = ["derive"] }
serde_yaml = "0.9.34"
serde_json = "1.0.133"

async-trait = "0.1.83"
futures = "0.3.31"

chrono = "0.4.38"
once_cell = "1.20.2"
rudi = "0.8.3"
regex = "1.11.1"
rand = "0.8.5"
anyhow = "1.0.94"
thiserror = { version = "2.0.8", optional = true }
bcrypt = "0.16.0"
jsonwebtoken = "9.3.0"
hashbrown = { version = "0.15.1", features = ["serde"] }
matchit = { version = "0.8.4", optional = true }
rust-embed-for-web = "11.2.1"

tracing = "0.1"
tracing-subscriber = { version = "0.3.0", features = [
    "fmt",
    "env-filter",
    "json",
    "chrono",
] }
tracing-appender = "0.2"

rbs = { version = "4.5", optional = true }
rbatis = { version = "4.5", optional = true }
rbdc = { version = "4.5", default-features = false, optional = true }
rbdc-pg = { version = "4.5", optional = true }
rbdc-mysql = { version = "4.5", optional = true }
rbdc-pool-fast = { version = "4.5", optional = true }

mongodb = { version = "3.2.0", optional = true, features = [
    "zstd-compression",
] }

redis = { version = "0.27.6", default-features = false, features = [
    "script",
    "json",
], optional = true }
deadpool-redis = { version = "0.18.0", optional = true }

minio-rsc = { version = "0.2.3", optional = true }

next-web-mq = { path = "../next-web-mq", version = "0.1.0", features = [
    "rabbitmq",
], optional = true }
next-web-mqtt = { path = "../next-web-mqtt", version = "0.1.0", optional = true }
next-web-common = { path = "../next-web-common", version = "0.1.0", default-features = false, futures = [
    "query-wrapper"
] }

[features]
default = [
    "database_enabled",
    "user_security",
    "mongodb_enabled",
    "rabbitmq_enabled",
]
tls_rustls = ["axum-server"]

redis_lock = ["thiserror"]
user_security = ["matchit"]
job_scheduler = ["tokio-cron-scheduler"]

grpc_enabled = []
prometheus_enabled = ["axum-prometheus"]

redis_enabled = ["redis", "deadpool-redis"]
database_enabled = ["rbs", "rbatis", "rbdc-pg", "rbdc-mysql", "rbdc-pool-fast"]
minio_enabled = ["minio-rsc"]
rabbitmq_enabled = ["next-web-mq"]
mqtt_enabled = ["next-web-mqtt"]
mongodb_enabled = ["mongodb"]
