[package]
name = "next-web-dev"
version = "0.1.0"
edition = "2021"
keywords = ["http", "web", "framework"]

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true, default-features = false, features = [
    "http2",
    "json",
    "tokio",
] }
axum-server = { version = "0.7.1", features = ["tls-rustls"], optional = true }
axum-prometheus = { workspace = true, optional = true }
tower-http = { workspace = true, features = [
    "trace",
    "timeout",
    "limit",
    "cors",
    "catch-panic",
] }
http-body-util = { workspace = true }
tokio-cron-scheduler = { workspace = true, optional = true }

serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }

async-trait = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
once_cell = { workspace = true }
hashbrown = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
regex = { workspace = true }
jsonwebtoken = { workspace = true }
rust-embed-for-web = { workspace = true }
matchit = { workspace = true, optional = true }
bcrypt = { workspace = true }
rand = { workspace = true }
parking_lot = { workspace = true }
flume = { workspace = true }

rudi = { workspace = true}

thiserror = { workspace = true, optional = true }

tracing-subscriber = { workspace = true }

rbs = { workspace = true, optional = true }
rbatis = { workspace = true, optional = true }
rbdc = { workspace = true, default-features = false, optional = true }
rbdc-pg = { workspace = true, optional = true }
rbdc-mysql = { workspace = true, optional = true }
rbdc-pool-fast = { workspace = true, optional = true }

mongodb = { workspace = true, optional = true }
redis = { workspace = true, optional = true }
deadpool-redis = { workspace = true, optional = true }
minio-rsc = { workspace = true, optional = true }

# self dependencies
next-web-core = { path = "../next-web-core", version = "0.1.0"}
next-web-mq = { path = "../next-web-mq", version = "0.1.0", features = [
    "rabbitmq",
], optional = true }
next-web-mqtt = { path = "../next-web-mqtt", version = "0.1.0", optional = true }
next-web-common = { path = "../next-web-common", version = "0.1.0", default-features = false, features = [
    "query-wrapper",
] }

[features]
default = [
    "database_enabled",
    "user_security",
    "mongodb_enabled",
    "rabbitmq_enabled",
]
tls_rustls = ["axum-server"]

redis_lock = ["thiserror"]
user_security = ["matchit"]
job_scheduler = ["tokio-cron-scheduler"]

grpc_enabled = []
prometheus_enabled = ["axum-prometheus"]

redis_enabled = ["redis", "deadpool-redis"]
database_enabled = ["rbs", "rbatis", "rbdc-pg", "rbdc-mysql", "rbdc-pool-fast"]
minio_enabled = ["minio-rsc"]
rabbitmq_enabled = ["next-web-mq"]
mqtt_enabled = ["next-web-mqtt"]
mongodb_enabled = ["mongodb"]
