[package]
name = "next-web-dev"
version = "0.1.4"
edition = "2021"
keywords = ["http", "web", "framework"]
description = "Next Web Dev!"
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true, features = ["full"]}
axum = { workspace = true, features = [
    "http2",
    "json",
    "tokio",
] }
axum-server = { version = "0.7.1", features = ["tls-rustls"], optional = true }
axum-prometheus = { workspace = true, optional = true }
tower-http = { workspace = true, features = [
    "trace",
    "timeout",
    "limit",
    "cors",
    "catch-panic",
] }
http-body-util = { workspace = true }
tokio-cron-scheduler = { workspace = true, optional = true }

serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }

async-trait = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
once_cell = { workspace = true }
hashbrown = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
regex = { workspace = true }
jsonwebtoken = { workspace = true }
rust-embed-for-web = { workspace = true }
matchit = { workspace = true, optional = true }
bcrypt = { workspace = true }
rand = { workspace = true }
parking_lot = { workspace = true }
flume = { workspace = true }

rudi-dev = { workspace = true}

thiserror = { workspace = true, optional = true }

tracing-subscriber = { workspace = true }

rbs = { workspace = true, optional = true }
rbatis = { workspace = true, optional = true }
rbdc = { workspace = true, default-features = false, optional = true }
rbdc-pg = { workspace = true, optional = true }
rbdc-mysql = { workspace = true, optional = true }
rbdc-pool-fast = { workspace = true, optional = true }

mongodb = { workspace = true, optional = true }
redis = { workspace = true, optional = true }
deadpool-redis = { workspace = true, optional = true }
minio-rsc = { workspace = true, optional = true }

# self dependencies
next-web-core = { workspace = true }
next-web-common = { version = "0.1.0", default-features = false, features = [
    "query-wrapper",
] }

[features]
default = [
    "database_enabled",
    "user_security",
    "mongodb_enabled",
    "job_scheduler"
]
tls_rustls = ["axum-server"]

redis_lock = ["thiserror"]
user_security = ["matchit"]
job_scheduler = ["tokio-cron-scheduler"]

grpc_enabled = []
prometheus_enabled = ["axum-prometheus"]

redis_enabled = ["redis", "deadpool-redis"]
database_enabled = ["rbs", "rbatis", "rbdc-pg", "rbdc-mysql", "rbdc-pool-fast"]
minio_enabled = ["minio-rsc"]
# rabbitmq_enabled = ["next-web-mq"]
mongodb_enabled = ["mongodb"]
