[package]
name = "next-web-examples"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
next-web                = { path = "../next-web", version = "*", features = ["full"]}
next-web-core           = { path = "../next-web-core", version = "*" }
next-web-context        = { path = "../next-web-context", version = "*" }
next-web-ai             = { path = "../next-web-ai", version = "*", features = ["deep-seek"]}
next-web-mqtt           = { path = "../next-web-mqtt", version = "*" }
next-web-websocket      = { path = "../next-web-websocket", version = "*" }
next-web-security       = { path = "../next-web-security", version = "*" }
next-web-data-redis     = { path = "../next-web-data/next-web-data-redis", version = "*", features = []}
next-web-data-database  = { path = "../next-web-data/next-web-data-database", version = "*" }
next-web-state-machine  = { path = "../next-web-state-machine", version = "*" }
next-web-xxl-job        = { path = "../next-web-xxl-job", version = "*" }
next-web-mail           = { path = "../next-web-mail", version = "*" }
next-web-ip             = { path = "../next-web-ip", version = "*" }
next-web-document       = { path = "../next-web-document", version = "*", features = [] }
next-web-retry          = { path = "../next-web-retry", version = "*" }
next-web-pay-alipay     = { path = "../next-web-pay/next-web-pay-alipay", version = "*" }

# next-web-data-database = { path = "../next-web-data-database", version = "*" }
# next-web-data-mongodb = { path = "../next-web-data-mongodb", version = "*" }

tokio           = { workspace = true, features = ["sync"]}
serde           = { workspace = true }
serde_json      = { workspace = true }

rust_xlsxwriter = { workspace = true }
axum            = { version = "0.8.4", features = ["default", "multipart", "query"] }
tokio-util      = { workspace = true }
futures         = { workspace = true }
utoipa          = { workspace = true }

tracing         = { workspace = true}

[features]
enable-api-doc = ["next-web/enable-api-doc"]

[[bin]]
name = "ai"
path = "ai.rs"

[[bin]]
name = "api_doc"
path = "api_doc.rs"

[[bin]]
name = "application"
path = "application.rs"

[[bin]]
name = "application_event"
path = "application_event.rs"

[[bin]]
name = "application_lifecycle"
path = "application_lifecycle.rs"

[[bin]]
name = "auto_configuration"
path = "auto_configuration.rs"

[[bin]]
name = "data"
path = "data.rs"

[[bin]]
name = "database"
path = "database.rs"

[[bin]]
name = "decoder_and_vaild"
path = "decoder_and_vaild.rs"

[[bin]]
name = "desensitized"
path = "desensitized.rs"

[[bin]]
name = "i18n"
path = "i18n.rs"

[[bin]]
name = "mail"
path = "mail.rs"

[[bin]]
name = "mqtt"
path = "mqtt.rs"

[[bin]]
name = "pay"
path = "pay.rs"

[[bin]]
name = "properties"
path = "properties.rs"

[[bin]]
name = "redis"
path = "redis.rs"

[[bin]]
name = "retry"
path = "retry.rs"

[[bin]]
name = "scheduled"
path = "scheduled.rs"

[[bin]]
name = "security"
path = "security.rs"

[[bin]]
name = "singleton"
path = "singleton.rs"

[[bin]]
name = "state_machine"
path = "state_machine.rs"

[[bin]]
name = "stream"
path = "stream.rs"

[[bin]]
name = "ws"
path = "ws.rs"

[[bin]]
name = "xxl_job"
path = "xxl_job.rs"
