pub mod bearer_token_authentication_filter;
pub mod logout;
pub mod ott;
pub mod preauth;
pub mod rememberme;
pub mod session;

pub mod switchuser;
pub mod ui;
pub mod www;

mod anonymous_authentication_filter;
mod authentication_converter;
mod authentication_failure_handler;
mod authentication_filter;
mod authentication_success_handler;
mod base_authentication_processing_filter;
mod base_authentication_target_url_request_handler;
mod basic_authentication_entry_point;
mod basic_authentication_filter;
mod delegating_authentication_entry_point;
mod forward_authentication_failure_handler;
mod forward_authentication_success_handler;
mod http403_forbidden_entry_point;
mod http_status_entry_point;
mod login_url_authentication_entry_point;
mod oauth2_authorization_code_grant_filter;
mod oauth2_authorization_request_redirect_filter;
mod oauth2_login_authentication_filter;
mod remember_me_authentication_filter;
mod remember_me_services;
mod saved_request_aware_authentication_success_handler;
mod simple_url_authentication_failure_handler;
mod simple_url_authentication_success_handler;
mod username_password_authentication_filter;
mod web_authentication_details;
mod web_authentication_details_source;

pub use anonymous_authentication_filter::AnonymousAuthenticationFilter;
pub use bearer_token_authentication_filter::BearerTokenAuthenticationFilter;
pub use authentication_converter::AuthenticationConverter;
pub use authentication_failure_handler::AuthenticationFailureHandler;
pub use authentication_filter::AuthenticationFilter;
pub use authentication_success_handler::AuthenticationSuccessHandler;
pub use base_authentication_processing_filter::BaseAuthenticationProcessingFilter;
pub use base_authentication_target_url_request_handler::BaseAuthenticationTargetUrlRequestHandler;
pub use basic_authentication_entry_point::BasicAuthenticationEntryPoint;
pub use basic_authentication_filter::BasicAuthenticationFilter;
pub use delegating_authentication_entry_point::{
    DelegatingAuthenticationEntryPoint, DelegatingAuthenticationEntryPointBuilder,
};
pub use forward_authentication_failure_handler::ForwardAuthenticationFailureHandler;
pub use forward_authentication_success_handler::ForwardAuthenticationSuccessHandler;
pub use http403_forbidden_entry_point::Http403ForbiddenEntryPoint;
pub use http_status_entry_point::HttpStatusEntryPoint;
pub use login_url_authentication_entry_point::LoginUrlAuthenticationEntryPoint;
pub use oauth2_authorization_code_grant_filter::OAuth2AuthorizationCodeGrantFilter;
pub use oauth2_authorization_request_redirect_filter::OAuth2AuthorizationRequestRedirectFilter;
pub use oauth2_login_authentication_filter::{
    OAuth2LoginAuthenticationFilter, OAuth2LoginRequestMatcher,
};
pub use remember_me_authentication_filter::RememberMeAuthenticationFilter;
pub use remember_me_services::RememberMeServices;
pub use saved_request_aware_authentication_success_handler::SavedRequestAwareAuthenticationSuccessHandler;
pub use simple_url_authentication_failure_handler::SimpleUrlAuthenticationFailureHandler;
pub use simple_url_authentication_success_handler::SimpleUrlAuthenticationSuccessHandler;
pub use username_password_authentication_filter::UsernamePasswordAuthenticationFilter;
pub use web_authentication_details::WebAuthenticationDetails;
pub use web_authentication_details_source::WebAuthenticationDetailsSource;

pub type AuthPrincipal = std::sync::Arc<dyn std::any::Any + Send + Sync>;
