[package]
name = "next-web-security-core"
version = "0.1.0"
edition = "2024"

[dependencies]
next-web-core = { workspace = true }
rudi-dev = { workspace = true }
axum = { workspace = true, features = ["http1"]}

bcrypt = { workspace = true }

matchit = { workspace = true }