[package]
name = "next-web-document"
version = "0.1.0"
edition = "2021"

[dependencies]
# calamine = { workspace = true, optional = true}


[features]
default = ["excel"]
excel = []
# excel = ["rust_xlsxwriter", "calamine"]
docx = []
