[package]
name = "next-web-tests"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
include.workspace = true
readme.workspace = true
version.workspace = true

[dependencies]
next-web-dev = { path = "../next-web-dev", version = "0.1.0" }
tokio = { workspace = true }
serde ={ workspace = true}
next-web-core = { path = "../next-web-core", version = "0.1.0" }
next-web-ip ={ path = "../next-web-ip", version = "0.1.0" }
next-web-macro ={ path = "../next-web-macro", version = "0.1.0" }
axum = { workspace = true}

[lints]
workspace = true
