[package]
name = "next-web-context"
edition.workspace = true
version.workspace = true
authors.workspace = true
keywords.workspace = true
license.workspace = true


[dependencies]
arc-swap.workspace      = true
async-trait.workspace   = true
dyn-clone.workspace     = true
indexmap.workspace      = true
inventory.workspace     = true
next-web-singletons     = { workspace = true }
tokio.workspace         = true
tracing.workspace       = true

[lints]
workspace = true
