#[rustfmt::skip]
pub const FIRST_NAMES: [&str; 138] =  [
    "James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda", 
    "William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica", 
    "Thomas", "Sarah", "Charles", "Karen", "Christopher", "Nancy", "Daniel", "Lisa", 
    "Matthew", "Betty", "Anthony", "Helen", "Mark", "Sandra", "Donald", "Donna", 
    "Steven", "Carol", "Paul", "Ruth", "Andrew", "Sharon", "Joshua", "Michelle", 
    "Kenneth", "Laura", "Kevin", "Kimberly", "Brian", "Deborah", "George", "Amy", 
    "Timothy", "Angela", "Ronald", "Melissa", "Jason", "Brenda", "Jeffrey", "Emma", 
    "Ryan", "Anna", "Jacob", "Dorothy", "Gary", "Christine", "Nicholas", "Alice", 
    "Eric", "Catherine", "Stephen", "Kathleen", "Jonathan", "Frances", "Larry", "Ann", 
    "Justin", "Joyce", "Scott", "Diane", "Brandon", "Julie", "Benjamin", "Heather", 
    "Samuel", "Joan", "Gregory", "Martha", "Alexander", "Judith", "Frank", "Cheryl", 
    "Patrick", "Megan", "Raymond", "Andrea", "Jack", "Olivia", "Dennis", "Jacqueline", 
    "Jerry", "Jean", "Tyler", "Gloria", "Aaron", "Teresa", "Jose", "Sara", "Adam", 
    "Janet", "Nathan", "Madison", "Henry", "Catherine", "Zachary", "Abigail", 
    "Douglas", "Sophia", "Peter", "Alexis", "Kyle", "Avery", "Noah", "Evelyn", 
    "Ethan", "Clara", "Jeremy", "Grace", "Walter", "Victoria", "Christian", "Aubrey", 
    "Keith", "Brianna", "Roger", "Lily", "Terry", "Hannah", "Joe", "Maria", "Austin", "Kayla"
];

/// 常见英文姓氏列表 (Last Names)
#[rustfmt::skip]
pub const LAST_NAMES: [&str; 513] = [
    "Smith", "Johnson", "Williams", "Jones", "Brown", "Davis", "Miller", "Wilson", 
    "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", 
    "Thompson", "Garcia", "Martinez", "Robinson", "Clark", "Rodriguez", "Lewis", 
    "Lee", "Walker", "Hall", "Allen", "Young", "Hernandez", "King", "Wright", "Lopez", 
    "Hill", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson", "Carter", 
    "Mitchell", "Perez", "Roberts", "Turner", "Phillips", "Campbell", "Parker", 
    "Evans", "Edwards", "Collins", "Stewart", "Sanchez", "Morris", "Rogers", "Reed", 
    "Cook", "Morgan", "Bell", "Murphy", "Bailey", "Rivera", "Cooper", "Richardson", 
    "Cox", "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez", "James", 
    "Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood", "Barnes", 
    "Ross", "Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long", "Patterson", 
    "Hughes", "Flores", "Washington", "Butler", "Simmons", "Foster", "Gonzales", 
    "Bryant", "Alexander", "Russell", "Griffin", "Diaz", "Hayes", "Myers", "Ford", 
    "Hamilton", "Graham", "Sullivan", "Wallace", "Woods", "Cole", "West", "Jordan", 
    "Owens", "Reynolds", "Fisher", "Ellis", "Harrison", "Gibson", "McDonald", 
    "Cruz", "Marshall", "Ortiz", "Gomez", "Murray", "Freeman", "Wells", "Webb", 
    "Simpson", "Stevens", "Tucker", "Porter", "Hunter", "Hicks", "Crawford", "Henry", 
    "Boyd", "Mason", "Morales", "Kennedy", "Warren", "Dixon", "Ramos", "Reyes", 
    "Burns", "Gordon", "Shaw", "Holmes", "Rice", "Robertson", "Hunt", "Black", 
    "Daniels", "Palmer", "Mills", "Nichols", "Grant", "Knight", "Ferguson", "Rose", 
    "Stone", "Hawkins", "Dunn", "Perkins", "Hudson", "Spencer", "Gardner", "Stephens", 
    "Payne", "Pierce", "Berry", "Matthews", "Arnold", "Wagner", "Willis", "Ray", 
    "Watkins", "Olson", "Carroll", "Duncan", "Snyder", "Hart", "Cunningham", "Bradley", 
    "Lane", "Andrews", "Ruiz", "Harper", "Fox", "Riley", "Armstrong", "Carpenter", 
    "Weaver", "Greene", "Lawrence", "Elliott", "Chavez", "Sims", "Austin", "Peters", 
    "Kelley", "Franklin", "Lawson", "Fields", "Gutierrez", "Ryan", "Schmidt", "Carr", 
    "Vasquez", "Castillo", "Wheeler", "Chapman", "Oliver", "Montgomery", "Richards", 
    "Williamson", "Johnston", "Banks", "Meyer", "Bishop", "McCoy", "Howell", "Alvarez", 
    "Morrison", "Hansen", "Fernandez", "Garza", "Harvey", "Little", "Burton", "Stanley", 
    "Nguyen", "George", "Jacobs", "Reid", "Kim", "Fuller", "Lynch", "Dean", "Gilbert", 
    "Garrett", "Romero", "Welch", "Larson", "Frazier", "Burke", "Hanson", "Day", 
    "Mendoza", "Moreno", "Bowman", "Medina", "Fowler", "Brewer", "Hoffman", "Carlson", 
    "Silva", "Pearson", "Holland", "Douglas", "Fleming", "Jensen", "Vargas", "Byrd", 
    "Davidson", "Hopkins", "May", "Terry", "Herrera", "Wade", "Soto", "Walters", 
    "Curtis", "Neal", "Caldwell", "Lowe", "Jennings", "Barnett", "Graves", "Jimenez", 
    "Horton", "Shelton", "Barrett", "Obrien", "Castro", "Sutton", "Gregory", "McKinney", 
    "Lucas", "Miles", "Craig", "Rodriquez", "Chambers", "Holt", "Lambert", "Fletcher", 
    "Watts", "Bates", "Hale", "Rhodes", "Pena", "Beck", "Newman", "Haynes", "McDaniel", 
    "Mendez", "Bush", "Vaughn", "Parks", "Dawson", "Santiago", "Norris", "Hardy", 
    "Love", "Steele", "Curry", "Powers", "Schultz", "Barker", "Guzman", "Page", 
    "Munoz", "Ball", "Keller", "Chandler", "Weber", "Leonard", "Walsh", "Lyons", 
    "Ramsey", "Wolfe", "Schneider", "Mullins", "Benson", "Sharp", "Bowen", "Daniel", 
    "Barber", "Cummings", "Hines", "Baldwin", "Griffith", "Valdez", "Hubbard", 
    "Salazar", "Reeves", "Warner", "Stanton", "Buck", "Holman", "England", "Dominguez", 
    "Mercado", "Hudson", "Norton", "McCall", "Gill", "Short", "Newton", "Todd", 
    "Blair", "Higgins", "Ingram", "Reese", "Cannon", "Strickland", "Townsend", "Potter", 
    "Goodwin", "Walter", "Butler", "Malone", "Shepherd", "Sherman", "Fry", "Vega", 
    "Mahoney", "Elliott", "Ochoa", "Becker", "Workman", "Luna", "Hensley", "Delgado", 
    "Brock", "Maynard", "Conner", "Pittman", "Wiley", "Salinas", "Velez", "Pratt", 
    "Muller", "Madden", "Kaufman", "Beach", "Goff", "Deleon", "Meadows", "Forbes", 
    "Fischer", "Gilliam", "Dejesus", "Bonner", "Morin", "Stafford", "Autry", "Grimes", 
    "Stein", "Levy", "York", "Whitfield", "Duke", "Odom", "Morse", "Sheppard", 
    "Snow", "Rosal", "Bolton", "Mays", "Rocha", "Melton", "Bray", "Oneill", "Blankenship", 
    "Benton", "Frye", "Barron", "Mejia", "Branch", "Spears", "Chase", "Dickson", 
    "Mckay", "Herman", "Sparks", "Mcguire", "Vincent", "Flynn", "Tyson", "Shields", 
    "Holmes", "Strong", "Prince", "Mcclure", "Conway", "Walter", "Roth", "Mayo", 
    "Fritz", "Hutchinson", "Mahoney", "Jefferson", "Hahn", "Gilliland", "Parrish", 
    "Alston", "Burnett", "Kline", "Whitaker", "Oconnell", "Hobbs", "Norman", "Hickman", 
    "Swanson", "Franco", "Rowland", "Sykes", "Benjamin", "Trujillo", "Tanner", "Winters", 
    "Meade", "Hutchins", "Bond", "Westmoreland", "Best", "Tobin", "Holley", "Kerr", 
    "Elmore", "Ashley", "Whitley", "Brewton", "Howe", "Addington", "Dunlap", "Bolin", 
    "Barnhill", "Mcneil", "Corbett", "Stevenson", "Hollis", "Womack", "Baird", 
    "Cato", "Henson", "Holliman", "Wooten", "Whitworth", "Keen", "Whitten", "Hagood", 
    "Mccollum", "Peacock", "Burch", "Mcmahon", "Whitton", "Henson", "Cagle", "Whitson", 
    "Hightower", "Wilkerson", "Whitson", "Hightower", "Wilkerson"
];

///
pub const COUNTRIES: [&str; 261] = [
    "王", "李", "张", "刘", "陈", "杨", "赵", "黄", "周", "吴", "徐", "孙", "胡", "朱", "高", "林",
    "何", "郭", "马", "罗", "梁", "宋", "郑", "谢", "韩", "唐", "冯", "于", "董", "萧", "程", "曹",
    "袁", "邓", "许", "傅", "沈", "曾", "彭", "吕", "苏", "卢", "蒋", "蔡", "贾", "丁", "魏", "薛",
    "叶", "阎", "余", "潘", "杜", "戴", "夏", "钟", "汪", "田", "任", "姜", "范", "方", "石", "姚",
    "谭", "廖", "邹", "熊", "金", "陆", "郝", "孔", "白", "崔", "康", "毛", "邱", "秦", "江", "史",
    "顾", "侯", "邵", "孟", "龙", "万", "段", "雷", "钱", "汤", "尹", "黎", "易", "常", "武", "乔",
    "贺", "赖", "龚", "文", "牛", "温", "莫", "席", "晏", "鲁", "韦", "申", "尤", "毕", "聂", "丛",
    "焦", "向", "柳", "邢", "路", "岳", "齐", "沿", "梅", "莫", "庄", "辛", "管", "祝", "左", "涂",
    "谷", "祁", "时", "舒", "耿", "牟", "卜", "路", "詹", "关", "苗", "凌", "费", "纪", "靳", "盛",
    "童", "欧", "甄", "项", "曲", "成", "游", "阳", "裴", "席", "卫", "查", "屈", "鲍", "隗", "商",
    "蒙", "蒲", "邰", "宫", "景", "米", "柏", "柏", "岑", "桑", "桂", "闵", "欧阳", "太史", "端木",
    "上官", "司马", "东方", "南宫", "西门", "北冥", "令狐", "皇甫", "诸葛", "尉迟", "公羊", "澹台",
    "公冶", "宗政", "濮阳", "淳于", "单于", "太叔", "申屠", "公孙", "仲孙", "轩辕", "令狐", "徐离",
    "宇文", "长孙", "慕容", "司徒", "司空", "鲜于", "闾丘", "司寇", "亓官", "司城", "子车", "颛孙",
    "端木", "巫马", "公西", "漆雕", "乐正", "壤驷", "公良", "拓跋", "夹谷", "宰父", "谷梁", "段干",
    "百里", "东郭", "南门", "呼延", "羊舌", "微生", "梁丘", "左丘", "东门", "西门", "南宫", "第五",
    "公乘", "公冶", "公皙", "公伯", "公祖", "公西", "公良", "公肩", "公户", "公玉", "公仪", "公仲",
    "公上", "公户", "公山", "公坚", "公乘", "公皙", "公祖", "公西", "公良", "公肩", "公玉", "公仪",
    "公仲", "公上",
];

// 常见的中文名字用字 (可用于名的第一个字和第二个字)
pub const CHINESE_NAMES: [&str; 647] = [
    "伟", "芳", "娜", "秀英", "敏", "静", "丽", "强", "磊", "军", "洋", "勇", "艳", "杰", "娟",
    "涛", "明", "超", "秀兰", "霞", "平", "华", "红", "斌", "桂英", "玲", "小", "宏", "志", "晶",
    "健", "淑珍", "启", "淑华", "建国", "国平", "国庆", "建平", "立", "文", "永", "雪", "梅", "海",
    "秀梅", "晓", "玉", "忠", "萍", "艳丽", "爱华", "春", "燕", "淑兰", "根", "鹏", "秀珍", "彦",
    "波", "颖", "俊", "浩", "淑琴", "家", "荣", "淑芳", "亮", "庆", "丽华", "建华", "德", "素珍",
    "世", "玉兰", "桂荣", "慧", "保", "桂兰", "秀英", "学", "玉梅", "树", "彦", "瑞", "淑云", "凤",
    "秀荣", "振", "秀兰", "桂珍", "淑英", "连", "秀英", "春梅", "丽娟", "桂芳", "素兰", "丽萍",
    "淑英", "秀兰", "秀英", "秀英", "秀英", "秀英", "一", "二", "三", "四", "五", "六", "七", "八",
    "九", "十", "百", "千", "万", "亿", "兆", "天", "地", "人", "和", "安", "宁", "福", "寿", "康",
    "泰", "祥", "瑞", "吉", "利", "德", "仁", "义", "礼", "智", "信", "忠", "孝", "廉", "节", "勇",
    "刚", "毅", "谦", "诚", "实", "真", "善", "美", "雅", "俊", "逸", "轩", "涵", "博", "渊", "浩",
    "瀚", "宇", "宙", "星", "辰", "日", "月", "光", "辉", "晨", "曦", "朝", "阳", "晚", "霞", "山",
    "水", "河", "海", "江", "湖", "松", "竹", "梅", "兰", "菊", "荷", "枫", "柳", "云", "风", "雨",
    "雪", "霜", "露", "电", "雷", "春", "夏", "秋", "冬", "花", "草", "飞", "翔", "腾", "跃", "驰",
    "骋", "翔", "宇", "天", "翔", "远", "航", "志", "远", "鹏", "程", "万", "里", "海", "阔", "凭",
    "鱼", "跃", "天", "高", "任", "鸟", "飞", "明", "哲", "保", "身", "厚", "德", "载", "物", "自",
    "强", "不", "息", "心", "想", "事", "成", "好", "梦", "成", "真", "鹏", "程", "万", "里", "前",
    "程", "似", "锦", "龙", "腾", "虎", "跃", "风", "和", "日", "丽", "国", "泰", "民", "安", "四",
    "海", "升", "平", "五", "谷", "丰", "登", "六", "畜", "兴", "旺", "七", "彩", "祥", "云", "八",
    "面", "威", "风", "九", "天", "揽", "月", "十", "全", "十", "美", "百", "年", "好", "合", "千",
    "里", "姻", "缘", "万", "象", "更", "新", "亿", "万", "富", "翁", "兆", "事", "如", "意", "金",
    "玉", "满", "堂", "锦", "上", "添", "花", "花", "好", "月", "圆", "珠", "联", "璧", "合", "琴",
    "瑟", "和", "鸣", "龙", "凤", "呈", "祥", "喜", "气", "盈", "门", "吉", "星", "高", "照", "福",
    "如", "东", "海", "寿", "比", "南", "山", "寿", "与", "天", "齐", "松", "鹤", "延", "年", "龟",
    "龄", "鹤", "寿", "万", "寿", "无", "疆", "福", "寿", "双", "全", "福", "禄", "寿", "喜", "五",
    "福", "临", "门", "天", "官", "赐", "福", "迎", "祥", "纳", "福", "招", "财", "进", "宝", "日",
    "进", "斗", "金", "财", "源", "广", "进", "金", "玉", "满", "堂", "堆", "金", "积", "玉", "富",
    "可", "敌", "国", "腰", "缠", "万", "贯", "锦", "衣", "玉", "食", "荣", "华", "富", "贵", "高",
    "官", "厚", "禄", "平", "步", "青", "云", "飞", "黄", "腾", "达", "出", "将", "入", "相", "位",
    "极", "人", "臣", "功", "德", "无", "量", "德", "高", "望", "重", "众", "望", "所", "归", "名",
    "扬", "四", "海", "誉", "满", "全", "球", "流", "芳", "百", "世", "万", "古", "流", "芳", "永",
    "垂", "不", "朽", "青", "史", "留", "名", "名", "垂", "青", "史", "功", "标", "青", "史", "彪",
    "炳", "千", "秋", "光", "耀", "门", "楣", "光", "宗", "耀", "祖", "扬", "眉", "吐", "气", "吐",
    "气", "扬", "眉", "意", "气", "风", "发", "神", "采", "奕", "奕", "容", "光", "焕", "发", "精",
    "神", "百", "倍", "生", "龙", "活", "虎", "龙", "马", "精", "神", "健", "步", "如", "飞", "身",
    "强", "体", "壮", "虎", "背", "熊", "腰", "孔", "武", "有", "力", "英", "姿", "飒", "爽", "风",
    "度", "翩", "翩", "玉", "树", "临", "风", "貌", "美", "如", "花", "闭", "月", "羞", "花", "沉",
    "鱼", "落", "雁", "国", "色", "天", "香", "倾", "国", "倾", "城", "花", "容", "月", "貌", "明",
    "眸", "皓", "齿", "亭", "亭", "玉", "立", "婀", "娜", "多", "姿", "楚", "楚", "动", "人", "小",
    "家", "碧", "玉", "大", "家", "闺", "秀", "秀", "外", "慧", "中", "知", "书", "达", "理", "温",
    "文", "尔", "雅", "贤", "良", "淑", "德", "秀", "外", "慧", "中", "知", "书", "达", "理", "温",
    "文", "尔", "雅", "贤", "良", "淑", "德",
];

pub const EMAIL_DOMAINS: [&str; 9] = [
    "gmail.com",
    "yahoo.com",
    "outlook.com",
    "163.com",
    "qq.com",
    "sina.com",
    "sohu.com",
    "tom.com",
    "aliyun.com",
];

pub const MOBILE_PREFIXES: [&str; 53] = [
    // 中国移动
    "134", "135", "136", "137", "138", "139", "147", "150", "151", "152", "157", "158", "159",
    "178", "182", "183", "184", "187", "188", "195", "197", "198", // 中国联通
    "130", "131", "132", "145", "155", "156", "166", "167", "171", "175", "176", "185", "186",
    "196", // 中国电信
    "133", "149", "153", "170", "173", "174", "177", "180", "181", "189", "190", "191", "193",
    "199", // 中国广电
    "192", // 虚拟运营商 (MVNO)
    "162", "165",
    // 注意: 170 和 171 已在联通和电信中列出，这里不再重复
];

pub const PROTOCOLS: [&str; 9] = [
    "http", "https", "ftp", "ssh", "sftp", "ldap", "smtp", "pop3", "imap",
];