server_addr: 192.168.18.168

next:
  server:
    port: 11000
  application:
    name: "NextWebApplication"

  messages:
    local: "zh_CN"

  data:
    redis:
      host: "192.168.1.19"
      port: 6379
      password: "123"
      
  xxl_job:
    server_address: "127.0.0.1:11300"
    access_token: "null"
    app_name: ${next.application.name}
    log_path: "/app/next/xxl_job"

  tests:
    version: "1.0.0"
    model: "test"
    enable: true
    date: "2021-12-20"

  logging:
    format: "%Y-%m-%d %H:%M:%S%.3f"
    level: info

  feature:
    enabled: true
windows:
  computername: ${COMPUTERNAME}
