[package]
name = "next-web"
version = "0.2.1"
edition = "2021"
description = "Make everything simpler!"
homepage = "https://crates.io/crates/next-web"
keywords = ["http", "web", "framework"]
readme = "../README.md"
repository = "https://github.com/yuenxillar/next-web"
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
next-web-core           = { workspace = true }
next-web-context        = { workspace = true }
next-web-macros         = { workspace = true }

next-web-security       = { workspace = true, optional = true }
next-web-websocket      = { workspace = true, optional = true }
next-web-retry          = { workspace = true, optional = true }
next-web-api-doc        = { workspace = true, optional = true }
next-web-state-machine  = { workspace = true, optional = true }

tokio                   = { workspace = true, features = ["sync", "signal","net", "fs"] }
axum                    = { workspace = true, features = ["http2"] }
axum-core               = { workspace = true }
axum-server             = { version = "0.7.1", features = ["tls-rustls"], optional = true }
axum-prometheus         = { workspace = true, optional = true }
tower-http              = { workspace = true, features = [
    "trace",
    "timeout",
    "limit",
    "cors",
    "catch-panic",
] }
http-body-util          = { workspace = true }
tokio-cron-scheduler    = { workspace = true, optional = true }
rust-embed              = { workspace = true, optional = true }

serde               = { workspace = true }
serde_yaml          = { workspace = true }
serde_json          = { workspace = true }

tokio-util          = { workspace = true }
futures             = { workspace = true }
chrono              = { workspace = true }
chrono-tz           = { workspace = true }
once_cell           = { workspace = true }
tracing             = { workspace = true }
tracing-appender    = { workspace = true }
regex               = { workspace = true }
flume               = { workspace = true }
validator           = { workspace = true }
thiserror           = { workspace = true }
inventory           = { workspace = true }

utoipa-swagger-ui   = { workspace = true, optional = true }

rudi-dev            = { workspace = true }

tracing-subscriber  = { workspace = true }

reqwest             = { workspace = true, features = ["stream"] }
async-stream        = { workspace = true }

md5                 = { workspace = true, optional = true }
sha1                = { workspace = true, optional = true }
sha2                = { workspace = true, optional = true }
base64              = { workspace = true, optional = true }
aes-gcm             = { workspace = true, optional = true }
scrypt              = { workspace = true, optional = true }
rand                = { workspace = true, optional = true }

serde_path_to_error = { workspace = true }
mime                = { workspace = true }

uuid                = { workspace = true }

num_cpus            = { version = "1.17.0", optional = true }

[target.'cfg(windows)'.dependencies]
mimalloc        = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator    = { workspace = true }

[features]
default = ["decrypt-properties"]
full = [
    "enable-scheduling",
    "enable-web-security",
    "enable-retry",
    "enable-i18n",
    "enable-thread-pool",

    "common",

    "decrypt-properties",
    # "enable-api-doc",
    "trace-log"
]

rustls = ["axum-server"]

# web
enable-web-security     = ["next-web-security"]
enable-websocket        = ["next-web-websocket"]

enable-scheduling       = ["tokio-cron-scheduler"]
enable-retry            = ["next-web-retry"]
enable-api-doc          = ["next-web-api-doc", "utoipa-swagger-ui", "next-web-macros/api-doc"]
enable-prometheus       = ["axum-prometheus"]
enable-i18n             = ["next-web-macros/translation"]
enable-state-machine    = ["next-web-state-machine"]
enable-thread-pool      = ["num_cpus"]

embed-resources         = ["next-web-macros/embed-resources", "next-web-core/embed-resources", "dep:rust-embed"]

common                  = []

digester                = ["dep:md5", "dep:sha1", "dep:sha2"]
decrypt-properties      = ["aes-gcm", "dep:base64", "scrypt", "rand"]

trace-log               = ["next-web-core/trace-log"]
