test: "nihao"
next:
  server:
    port: 8080
    context_path: /test
  coco: "hello world111"

  data: 
    database:
      driver: mysql
      host: 192.168.1.117
      port: 3306
      username: root
      password: 123456
      database: next_web
    redis:
      host: 192.168.1.117
      port: 6379
      password: 123
      database: 0
    mongodb:
      host: 192.168.1.117
      port: 27017
      username: admin
      password: 123456
      database: next_web
  mqtt:
   host: 192.168.1.117
   port: 1883
   username: user1
   password: 123
   topics:
      - test/#
      - robot/#
   # from secs
   connect_timeout: 10
   clean_session: true
  ws:
    max_msg_size: 30000
    max_write_buffer_size: 131073
    max_session_idle_timeout: 30000