test: "nihao"
next:
  server:
    port: 8080
    context_path: /test
  coco: ${test}
  mqtt:
   host: localhost
   port: 1883
   username: user1
   password: 123
   topics:
      - test/#
      - robot/#
   # from secs
   connect_timeout: 10
   clean_session: true
  ws:
    max_msg_size: 30000
    max_write_buffer_size: 131073
    max_session_idle_timeout: 30000