test: "nihao"
next:
  server:
    port: 8080
    context_path: /test
  coco: ${test}

  data: 
    database:
      driver: mysql
      host: localhost
      port: 3306
      username: root
      password: 123456
      database: next_web
    redis:
      host: localhost
      port: 6379
      password: 123
      database: 0
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: 123456
      database: next_web
  mqtt:
   host: localhost
   port: 1883
   username: user1
   password: 123
   topics:
      - test/#
      - robot/#
   # from secs
   connect_timeout: 10
   clean_session: true
  ws:
    max_msg_size: 30000
    max_write_buffer_size: 131073
    max_session_idle_timeout: 30000