[package]
name = "next-web-mqtt"
version = "0.1.4"
edition = "2021"
description = "Next Web Mqtt."
license.workspace = true

[dependencies]
next-web-context.workspace = true
next-web-core   = { workspace = true }
next-web-macros = { workspace = true }

serde           = { workspace = true }
rumqttc         = { workspace = true }

tokio           = { workspace = true }
tracing         = { workspace = true }


[features]
trace-log = []
